// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: internalApi.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string `protobuf:"bytes,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *InternalApiRequest) Reset() {
	*x = InternalApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internalApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalApiRequest) ProtoMessage() {}

func (x *InternalApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalApiRequest.ProtoReflect.Descriptor instead.
func (*InternalApiRequest) Descriptor() ([]byte, []int) {
	return file_internalApi_proto_rawDescGZIP(), []int{0}
}

func (x *InternalApiRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InternalApiRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type InternalApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
}

func (x *InternalApiResponse) Reset() {
	*x = InternalApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internalApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalApiResponse) ProtoMessage() {}

func (x *InternalApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalApiResponse.ProtoReflect.Descriptor instead.
func (*InternalApiResponse) Descriptor() ([]byte, []int) {
	return file_internalApi_proto_rawDescGZIP(), []int{1}
}

func (x *InternalApiResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_internalApi_proto protoreflect.FileDescriptor

var file_internalApi_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x32, 0x4e, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70,
	0x69, 0x12, 0x3f, 0x0a, 0x02, 0x44, 0x6f, 0x12, 0x1a, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internalApi_proto_rawDescOnce sync.Once
	file_internalApi_proto_rawDescData = file_internalApi_proto_rawDesc
)

func file_internalApi_proto_rawDescGZIP() []byte {
	file_internalApi_proto_rawDescOnce.Do(func() {
		file_internalApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_internalApi_proto_rawDescData)
	})
	return file_internalApi_proto_rawDescData
}

var file_internalApi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internalApi_proto_goTypes = []interface{}{
	(*InternalApiRequest)(nil),  // 0: chorus.InternalApiRequest
	(*InternalApiResponse)(nil), // 1: chorus.InternalApiResponse
}
var file_internalApi_proto_depIdxs = []int32{
	0, // 0: chorus.InternalApi.Do:input_type -> chorus.InternalApiRequest
	1, // 1: chorus.InternalApi.Do:output_type -> chorus.InternalApiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internalApi_proto_init() }
func file_internalApi_proto_init() {
	if File_internalApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internalApi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internalApi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internalApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internalApi_proto_goTypes,
		DependencyIndexes: file_internalApi_proto_depIdxs,
		MessageInfos:      file_internalApi_proto_msgTypes,
	}.Build()
	File_internalApi_proto = out.File
	file_internalApi_proto_rawDesc = nil
	file_internalApi_proto_goTypes = nil
	file_internalApi_proto_depIdxs = nil
}
