// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalApiClient is the client API for InternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalApiClient interface {
	Do(ctx context.Context, in *InternalApiRequest, opts ...grpc.CallOption) (*InternalApiResponse, error)
}

type internalApiClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalApiClient(cc grpc.ClientConnInterface) InternalApiClient {
	return &internalApiClient{cc}
}

func (c *internalApiClient) Do(ctx context.Context, in *InternalApiRequest, opts ...grpc.CallOption) (*InternalApiResponse, error) {
	out := new(InternalApiResponse)
	err := c.cc.Invoke(ctx, "/chorus.InternalApi/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
