// This is a protobuf specifications for the SharedLinks module of the Third Light gRPC API for Chorus.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: sharedlinks.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Details about a shared link.
type SharedLinkDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The date/time that this object was created
	CreatedDate *DateTime `protobuf:"bytes,102,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	// A description for this Shared Link, which will get passed on to the link.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// ID of the special collection that backs this shared link.
	FolderId string `protobuf:"bytes,4,opt,name=folderId,proto3" json:"folderId,omitempty"`
	// Unique ID of this object.
	Id string `protobuf:"bytes,101,opt,name=id,proto3" json:"id,omitempty"`
	// The date/time that this object was last changed
	ModifiedDate *DateTime `protobuf:"bytes,103,opt,name=modifiedDate,proto3" json:"modifiedDate,omitempty"`
	// A convenient name for this Shared Link.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URLs for the shared link
	Urls []string `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *SharedLinkDetails) Reset() {
	*x = SharedLinkDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinkDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinkDetails) ProtoMessage() {}

func (x *SharedLinkDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinkDetails.ProtoReflect.Descriptor instead.
func (*SharedLinkDetails) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{0}
}

func (x *SharedLinkDetails) GetCreatedDate() *DateTime {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *SharedLinkDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SharedLinkDetails) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *SharedLinkDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SharedLinkDetails) GetModifiedDate() *DateTime {
	if x != nil {
		return x.ModifiedDate
	}
	return nil
}

func (x *SharedLinkDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SharedLinkDetails) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type SharedLinksRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SharedLinksRequests) Reset() {
	*x = SharedLinksRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinksRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinksRequests) ProtoMessage() {}

func (x *SharedLinksRequests) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinksRequests.ProtoReflect.Descriptor instead.
func (*SharedLinksRequests) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{1}
}

type SharedLinksResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SharedLinksResponses) Reset() {
	*x = SharedLinksResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinksResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinksResponses) ProtoMessage() {}

func (x *SharedLinksResponses) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinksResponses.ProtoReflect.Descriptor instead.
func (*SharedLinksResponses) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{2}
}

type SharedLinksRequests_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id, or array thereof, of the Shared Links of which to get the details.
	SharedLinkId string `protobuf:"bytes,1,opt,name=sharedLinkId,proto3" json:"sharedLinkId,omitempty"`
}

func (x *SharedLinksRequests_Get) Reset() {
	*x = SharedLinksRequests_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinksRequests_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinksRequests_Get) ProtoMessage() {}

func (x *SharedLinksRequests_Get) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinksRequests_Get.ProtoReflect.Descriptor instead.
func (*SharedLinksRequests_Get) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SharedLinksRequests_Get) GetSharedLinkId() string {
	if x != nil {
		return x.SharedLinkId
	}
	return ""
}

type SharedLinksRequests_GetMulti struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id, or array thereof, of the Shared Links of which to get the details.
	SharedLinkIds []string `protobuf:"bytes,1,rep,name=sharedLinkIds,proto3" json:"sharedLinkIds,omitempty"`
}

func (x *SharedLinksRequests_GetMulti) Reset() {
	*x = SharedLinksRequests_GetMulti{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinksRequests_GetMulti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinksRequests_GetMulti) ProtoMessage() {}

func (x *SharedLinksRequests_GetMulti) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinksRequests_GetMulti.ProtoReflect.Descriptor instead.
func (*SharedLinksRequests_GetMulti) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SharedLinksRequests_GetMulti) GetSharedLinkIds() []string {
	if x != nil {
		return x.SharedLinkIds
	}
	return nil
}

type SharedLinksResponses_GetMulti struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*SharedLinkDetails `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *SharedLinksResponses_GetMulti) Reset() {
	*x = SharedLinksResponses_GetMulti{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharedlinks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedLinksResponses_GetMulti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedLinksResponses_GetMulti) ProtoMessage() {}

func (x *SharedLinksResponses_GetMulti) ProtoReflect() protoreflect.Message {
	mi := &file_sharedlinks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedLinksResponses_GetMulti.ProtoReflect.Descriptor instead.
func (*SharedLinksResponses_GetMulti) Descriptor() ([]byte, []int) {
	return file_sharedlinks_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SharedLinksResponses_GetMulti) GetResponse() []*SharedLinkDetails {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_sharedlinks_proto protoreflect.FileDescriptor

var file_sharedlinks_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x1a, 0x0a, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x11, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x32, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x66, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x34, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x72, 0x0a,
	0x13, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x1a, 0x29, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x1a,
	0x30, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x64,
	0x73, 0x22, 0x59, 0x0a, 0x14, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x1a, 0x41, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xad, 0x01, 0x0a,
	0x0b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x43, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0x00, 0x12, 0x59, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x24, 0x2e,
	0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x1a, 0x25, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sharedlinks_proto_rawDescOnce sync.Once
	file_sharedlinks_proto_rawDescData = file_sharedlinks_proto_rawDesc
)

func file_sharedlinks_proto_rawDescGZIP() []byte {
	file_sharedlinks_proto_rawDescOnce.Do(func() {
		file_sharedlinks_proto_rawDescData = protoimpl.X.CompressGZIP(file_sharedlinks_proto_rawDescData)
	})
	return file_sharedlinks_proto_rawDescData
}

var file_sharedlinks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sharedlinks_proto_goTypes = []interface{}{
	(*SharedLinkDetails)(nil),             // 0: chorus.SharedLinkDetails
	(*SharedLinksRequests)(nil),           // 1: chorus.SharedLinksRequests
	(*SharedLinksResponses)(nil),          // 2: chorus.SharedLinksResponses
	(*SharedLinksRequests_Get)(nil),       // 3: chorus.SharedLinksRequests.Get
	(*SharedLinksRequests_GetMulti)(nil),  // 4: chorus.SharedLinksRequests.GetMulti
	(*SharedLinksResponses_GetMulti)(nil), // 5: chorus.SharedLinksResponses.GetMulti
	(*DateTime)(nil),                      // 6: chorus.DateTime
}
var file_sharedlinks_proto_depIdxs = []int32{
	6, // 0: chorus.SharedLinkDetails.createdDate:type_name -> chorus.DateTime
	6, // 1: chorus.SharedLinkDetails.modifiedDate:type_name -> chorus.DateTime
	0, // 2: chorus.SharedLinksResponses.GetMulti.response:type_name -> chorus.SharedLinkDetails
	3, // 3: chorus.SharedLinks.Get:input_type -> chorus.SharedLinksRequests.Get
	4, // 4: chorus.SharedLinks.GetMulti:input_type -> chorus.SharedLinksRequests.GetMulti
	0, // 5: chorus.SharedLinks.Get:output_type -> chorus.SharedLinkDetails
	5, // 6: chorus.SharedLinks.GetMulti:output_type -> chorus.SharedLinksResponses.GetMulti
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sharedlinks_proto_init() }
func file_sharedlinks_proto_init() {
	if File_sharedlinks_proto != nil {
		return
	}
	file_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sharedlinks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinkDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharedlinks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinksRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharedlinks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinksResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharedlinks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinksRequests_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharedlinks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinksRequests_GetMulti); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharedlinks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedLinksResponses_GetMulti); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sharedlinks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sharedlinks_proto_goTypes,
		DependencyIndexes: file_sharedlinks_proto_depIdxs,
		MessageInfos:      file_sharedlinks_proto_msgTypes,
	}.Build()
	File_sharedlinks_proto = out.File
	file_sharedlinks_proto_rawDesc = nil
	file_sharedlinks_proto_goTypes = nil
	file_sharedlinks_proto_depIdxs = nil
}
