// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpacesClient is the client API for Spaces service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpacesClient interface {
	// Get the details about a Space.
	Get(ctx context.Context, in *SpacesRequests_Get, opts ...grpc.CallOption) (*SpaceDetails, error)
	// Get the details about a Space.
	GetMulti(ctx context.Context, in *SpacesRequests_GetMulti, opts ...grpc.CallOption) (*SpacesResponses_GetMulti, error)
}

type spacesClient struct {
	cc grpc.ClientConnInterface
}

func NewSpacesClient(cc grpc.ClientConnInterface) SpacesClient {
	return &spacesClient{cc}
}

func (c *spacesClient) Get(ctx context.Context, in *SpacesRequests_Get, opts ...grpc.CallOption) (*SpaceDetails, error) {
	out := new(SpaceDetails)
	err := c.cc.Invoke(ctx, "/chorus.Spaces/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacesClient) GetMulti(ctx context.Context, in *SpacesRequests_GetMulti, opts ...grpc.CallOption) (*SpacesResponses_GetMulti, error) {
	out := new(SpacesResponses_GetMulti)
	err := c.cc.Invoke(ctx, "/chorus.Spaces/GetMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
